[package]
name = "sway-remap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evdev = "0.11.1"
uinput = "0.1.3"
uinput-sys = "0.1.7"
signal-hook = "0.3.11"
swayipc = "2.7.2"
